language: node_js
node_js:
  - "8.16"
  - "10.16"
sudo: false
cache: yarn

jobs:
  include:
    - stage: Produce Coverage
      node_js: "10.16"
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
